# AirBnB NY Locations Data Case Study

In this final project, you task will be to take the data provided and find evidance to answer the following questions.

1. Which hosts are the busiest and why?
2. How many neighborhood groups are available and which shows up the most?
3. Are private rooms the most popular in manhattan?
4. Which hosts are the busiest and based on their reviews?
5. Which neighorhood group has the highest average price?
6. Which neighborhood group has the highest total price?
7. Which top 5 hosts have the highest total price?
8. Who currently has no (zero) availability with a review count of 100 or more?
9. What host has the highest total of prices and where are they located?
10. When did Danielle from Queens last receive a review?

You will be given **4 hours** to complete this assignment. 
**Be Advised** I will go dark for this intire assignment time period. That said, any questions that you would like to ask about the data, or the project **MUST** be asked before the time starts. Once the time has started, I can no longer give information.

This is to similate what you will face when you are out in the wild. 

Happy Coding!

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
air_bnb = pd.read_csv('../files/AB_NYC_2019.csv')
air_bnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [76]:
# Which hosts are the busiest and why
host_count = air_bnb[['host_name', 'id']].groupby('host_id').count()
host_count.sort_values('id', ascending=False)
# show that the top host owning 327 airbnbs is host_id 219517861, 107434423, 30283594, 137358866, 16098958

# Checking host_id 219517861
bnb_copy = air_bnb
# bnb_copy.set_index('host_id',inplace = True)
# bnb_copy

# maybe make bin with ranks of numbers of airbnbs

bnb_copy.loc[[219517861, 107434423, 30283594, 137358866, 16098958]]

,id,name,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
host_id,,,,,,,,,,,,,,,
219517861,30181691,Sonder | 180 Water | Incredible 2BR + Rooftop,Sonder (NYC),Manhattan,Financial District,40.70637,-74.00645,Entire home/apt,302,29,0,NaN,NaN,327,309
219517861,30181945,Sonder | 180 Water | Premier 1BR + Rooftop,Sonder (NYC),Manhattan,Financial District,40.70771,-74.00641,Entire home/apt,229,29,1,2019-05-29,0.73,327,219
219517861,30347708,Sonder | 180 Water | Charming 1BR + Rooftop,Sonder (NYC),Manhattan,Financial District,40.70743,-74.00443,Entire home/apt,232,29,1,2019-05-21,0.60,327,159
219517861,30937590,Sonder | The Nash | Artsy 1BR + Rooftop,Sonder (NYC),Manhattan,Murray Hill,40.74792,-73.97614,Entire home/apt,262,2,8,2019-06-09,1.86,327,91
219517861,30937591,Sonder | The Nash | Lovely Studio + Rooftop,Sonder (NYC),Manhattan,Murray Hill,40.74771,-73.97528,Entire home/apt,255,2,14,2019-06-10,2.59,327,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16098958,33070416,Prime 1 bedroom Doorman Gym RoofDeck 5221,Jeremy & Laura,Manhattan,Midtown,40.74885,-73.98698,Entire home/apt,260,30,1,2019-05-06,0.46,96,343
16098958,33071794,Prime Location 44stDoorman Gym Studio!5217,Jeremy & Laura,Manhattan,Midtown,40.75032,-73.97143,Entire home/apt,175,30,0,NaN,NaN,96,342
16098958,33072686,Prime Location One Bed Doorman Gym Deck!5223,Jeremy & Laura,Manhattan,Hell's Kitchen,40.76291,-73.98750,Entire home/apt,250,30,0,NaN,NaN,96,303
16098958,33072804,34th and 6th Ave - Doorman Gym Roofdeck 1 bed ...,Jeremy & Laura,Manhattan,Midtown,40.74909,-73.98657,Entire home/apt,170,30,1,2019-05-12,0.51,96,345
16098958,33339676,Sunny Large Studio Elevator Doorman Gym UN 5226,Jeremy & Laura,Manhattan,Midtown,40.75191,-73.96980,Entire home/apt,140,30,0,NaN,NaN,96,311

In [ ]:
# How many neighborhood groups are available and which shows up the most?

In [ ]:
# Are private rooms the most popular in manhattan?

In [ ]:
# Which hosts are the busiest and based on their reviews?

In [ ]:
#Which neighorhood group has the highest average price?

In [ ]:
# Which neighbor hood group has the highest total price?

In [ ]:
#Which top 5 hosts have the highest total price?

In [ ]:
# Who currently has no (zero) availability with a review count of 100 or more?

In [ ]:
# What host has the highest total of prices and where are they located?

In [ ]:
# When did Danielle from Queens last receive a review?

## Further Questions

1. Which host has the most listings?

2. How many listings have completely open availability?

3. What room_types have the highest review numbers?

# Final Conclusion

In this cell, write your final conclusion for each of the questions asked.

Also, if you uncovered some more details that were not asked above, please discribe them here.

-- Add your conclusion --